version: "3"
services:
  typescript:
    build: .
    volumes: 
      - ./src/:/usr/src/app/src/
      - ./test/:/usr/src/app/test/
      - ./config.json:/user/src/app/config.json
    restart: on-failure
networks:
  dupbit_prime:
    external: true
